### ISSUE TITLE
Add a funtion in Route, Leg, and Step to return a friendlier string representation of the duration of the route

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#108]
Comment on "csmengwan" once this is done, please.

**Comment by dutchscout** [comment]
Moving this to V1.  I believe this would be implemented best by a single method in ui.utility to convert a time-duration in seconds to a user-readable string

**Comment by alaurenz** [comment]
I created a method to convert a time-duration in seconds to a user-readable string in the Utility class. I also made a method that calls this method to return a human-readable duration for the total route time and time of a step. I think it is unnecessary to have one for the leg class.
