### ISSUE TITLE
Adding set setMin/MaxDistanceToBikeInMeters() and setMin/MaxNumberBusTransfers() to UI?

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#115]
Are these backend functions working now? If yes, should I implement it for Beta? Under what travel mode should I provide user with these max-min options? Are they mutually exclusive?

**Comment by dutchscout** [comment]
@alaurenz is there any way your algorithms could use this information?  If not, we could simply filter the routes you return to the DirectionsRequest object, based on the options the user gave.

**Comment by CoolCapri** [comment]
Is this required for Beta? If not, I will change this issue to V1.

**Comment by CoolCapri** [comment]
Alright, for now I just change it to V1.

**Comment by CoolCapri** [comment]
OK I have added this.
