### ISSUE TITLE
Travel Mode Feature seems Not Working

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#117]
I have added Travel Mode Selection feature. It seems like no matter what mode I choose, the routes are the same. I have tried to print out travel mode once user select one, and I am sure the input to backend is correct (Since backend reports correctly the error messages for unsupported WALKING and UNKNOWN). Is this a bug, or this feature is still under development? Please try it.

**Comment by dutchscout** [comment]
This isn't currently doing much in the backend, but we could do filtering in DirectionsRequest object:
1) If bicycle mode only, return only the results of the simple bicycle algorithm
2) If transit only, return only the results of a (new) simple transit algorithm (that includes walking directions)
3) If mixed mode, continue as normal

@alaurenz I don't think there's a lot the algorithms could do with this information, but we could filter things in DirectionsRequest.  What do you think?

**Comment by dutchscout** [comment]
Also, @CoolCapri,  please remove walking and unknown options from the UI drop-down list, since these are not legal travel modes for making queries (they are in the enum to help represent results, but not queries).

**Comment by dutchscout** [comment]
Also, please set mixed mode as the default and replace the text 'Mixed' with something like 'Bicycle and transit', to try to make it more clear to the user.

**Comment by CoolCapri** [comment]
OK, I will change the number of options and the description this afternoon

**Comment by CoolCapri** [comment]
@csmengwan

**Comment by CoolCapri** [comment]
I have changed the number of options and the descriptions.
