### ISSUE TITLE
Add unit testing for ui utility class

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#121]
We need to increase our testing coverage!

**Comment by dutchscout** [comment]
I got this file started with one test case, but I'm not sure whether I'll have time to finish it myself.

**Comment by sw11** [comment]
Can you tell me what should I need to do about this?

**Comment by dutchscout** [comment]
Each of the methods (except a private constructor) need unit tests made for
them, covering cases that should work, cases that may fail, edge cases, and
typical cases, etc etc.

I'm not sure who will write these tests, but they need to be written this
phase so we can reach our test coverage goals.

On May 19, 2013, at 1:09, sw11 notifications@github.com wrote:

Can you tell me what should I need to do about this?

—
Reply to this email directly or view it on
GitHubhttps://github.com/alaurenz/metrobike/issues/121#issuecomment-18114015
.

**Comment by sw11** [comment]
MapSetting class cannot be tested since it needs googlemap object.
But historytest class is added.
