### ISSUE TITLE
Lower UI checkstyle problems

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#122]
There are currently 110 checkstyle warnings in the ui package.  Please make this much smaller...

(warnings as of build 53: http://nwebster.cs.washington.edu:8080/cse403/job/MetroBike/53/checkstyleResult/ )

**Comment by CoolCapri** [comment]
This is finished. Only 2-3 checkstyle issues remained because I don't know their usage.

**Comment by dutchscout** [comment]
Thank you for this!  Yay! most recent build gave only 26 CheckStyle warnings!
