### ISSUE TITLE
'Destination on your left' in the middle of a route

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#127]
We may not fix this issue but, when we combine directions, the instructions of a step in one of the earlier combined routes can say something about a destination, even though we're not at the end of our route.

For example, if we ask for directions from point A to point C, Google gives us walking directions from point A to point B and transit from point B to point C.  Then, we query for bicycle directions from point A to point B and put all of the results together.  However, since we individually queried for results from point A to point B, the instructions in the last step will tell us that our destination (referring to point B) will be on our left.

**Comment by CoolCapri** [comment]
Actually, I have found a way to strip it out on Details (I can simply strip out all the div tags and its inner contents) since the destination info is included in a div block. Do you want it?

**Comment by dutchscout** [comment]
That sounds great as long as we don't accidentally strip out anything we need.

**Comment by CoolCapri** [comment]
I have fixed it in DetailsActivity.

**Comment by CoolCapri** [comment]
Navigate Activity is also fixed.
