### ISSUE TITLE
App "crashes" when restart from eclipse

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#133]
This is a common bug that appear in Android app by using eclipse which may be we cannot do anything to fix it.
In addition, it won't crashed if only run on .apk file.
But I would like to address this issue just for reference

**Comment by CoolCapri** [comment]
Yes, I also noticed this problem. Not sure if we could do anything with it, though.

**Comment by sw11** [comment]
Here is the log. It seems that there is nothing we can do.
06-01 13:59:39.945: E/AndroidRuntime(15103): java.lang.RuntimeException: Unable to instantiate application android.app.Application: java.lang.NullPointerException
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.LoadedApk.makeApplication(LoadedApk.java:501)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4124)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.ActivityThread.access$1300(ActivityThread.java:130)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.os.Handler.dispatchMessage(Handler.java:99)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.os.Looper.loop(Looper.java:137)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.ActivityThread.main(ActivityThread.java:4745)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at java.lang.reflect.Method.invokeNative(Native Method)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at java.lang.reflect.Method.invoke(Method.java:511)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at dalvik.system.NativeStart.main(Native Method)
06-01 13:59:39.945: E/AndroidRuntime(15103): Caused by: java.lang.NullPointerException
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.LoadedApk.initializeJavaContextClassLoader(LoadedApk.java:377)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.LoadedApk.getClassLoader(LoadedApk.java:320)
06-01 13:59:39.945: E/AndroidRuntime(15103):    at android.app.LoadedApk.makeApplication(LoadedApk.java:493)
06-01 13:59:39.945: E/AndroidRuntime(15103):    ... 11 more
