### ISSUE TITLE
Add full repo access to TAs/Professor

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#14]
According to the ZFR doc:
"You must grant full access for the
instructor and TAs to your GitHub and Phabricator resources so that we can examine your work."

The professor seems to indicate this should already be possible by using email addresses to find git accounts.  See here:
https://catalyst.uw.edu/gopost/conversation/stepp/770415

**Comment by dutchscout** [comment]
@alaurenz Have you done this yet?

**Comment by alaurenz** [comment]
Yeah, searching by the full email did not come up with anything but when I just searched the parts before the @cs.washington.edu I found them (so I assume they are the correct accounts).
