### ISSUE TITLE
Jenkins build issue - test failed

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#142]
Failure in test_doRequestTest:
     [exec] junit.framework.AssertionFailedError: Actual status for request.doRequest() call was: Requested travel mode not supported. expected:<REQUEST_SUCCESSFUL> but was:<UNSUPPORTED_TRAVEL_MODE_ERROR>
     [exec]     at com.HuskySoft.metrobike.backend.test.DirectionsRequestTest.test_doRequestTest(DirectionsRequestTest.java:162)

**Comment by csmengwan** [comment]
I disable the travelMode transit last night, so who ever wrote the doRequestTest should take off the travelMode transit test case.

**Comment by dutchscout** [comment]
Working on it now...

**Comment by dutchscout** [comment]
Fixed!
