### ISSUE TITLE
String index out of bound exception

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#149]
If user set the current location on the from and to address, the app will crash with String index out of bound exception.

**Comment by sw11** [comment]
I just fix it by disable the other image button when current location is selected.
But is there any other solution apart from this?

**Comment by CoolCapri** [comment]
HI SAM I THINK YOU CAN REOPEN IT. I SAW ADRIAN FOXED THIS BUG. HE HAS JUST NOT PUSHED IT.

**Comment by sw11** [comment]
Adrian, can you push your fixed version so that we can test the app?
Thanks

**Comment by alaurenz** [comment]
Sorry I thought I had pushed the change. It should be updated now. Sorry for the delay, I didnt have net access for the weekend.
