### ISSUE TITLE
Wiki Post 6/2/13

### ISSUE THREAD

**Issue by coreyh3** [alaurenz/metrobike#150]

**Comment by dutchscout** [comment]
@coreyh3 when can you get this done?

**Comment by coreyh3** [comment]
@dutchscout 
I was midway through editing the tasks list of the wiki until it got updated. I've been waiting till the end so that the progress section is accurate.  
Either way, someone updated the last section before I hit save, so it's done now.
Corey

Date: Sun, 2 Jun 2013 23:03:35 -0700
