### ISSUE TITLE
timestampTo12HourTime in Utility returns the time for the wrong Locale.

### ISSUE THREAD

**Issue by coreyh3** [alaurenz/metrobike#154]
You need to use one of the factory methods in DateFormat instead of SimpleDateFormat

**Comment by coreyh3** [comment]
It looks like it is returning the time in GMT and not GMT-7.

**Comment by CoolCapri** [comment]
How about using hardcoded time (so that we don't have to consider time zone) since this test is just checking format.

**Comment by coreyh3** [comment]
Its now returning GMT-7.  The test was expecting GMT-7 and the code was returning GMT.  The method did note it was returning GMT.  Either way, if you want to change it back to GMT just remove the line that sets the Timezone.
