### ISSUE TITLE
Who should handle the cases when Minimum Number of Buses is greater than Maximum Number of Buses?

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#156]
I am adding number of buses options to the UI. Currently I am limiting user to input 0-99 for min/max number of buses (User can leave it blank and I will not set it in doRequest in this case). 

However, I have not checked where min <= max. I think it would be more uniform to let the backend handle this because we can simply display a new error message as we report other types of errors to users. What do you think?

**Comment by dutchscout** [comment]
validateParameters() in the RequestParameters object handles this.

Also, doRequest() in the DirectionsRequest object is responsible for filtering out the result routes, so you shouldn't need to check the minor options in RequestParameters inside the algorithm at all.

**Comment by dutchscout** [comment]
Oops, this is about UI.  You can validate if you'd like, but the backend should throw an error if you ask for bad options.

**Comment by CoolCapri** [comment]
Checking this in backend could help us create some test and increase our test coverage, so... 
I think I would simply not check this in SearchActivity, and report to user when backend reports this error.

**Comment by coreyh3** [comment]
Currently the backend returns INVALID_REQUEST_PARAMS after doRequest is called. So it is already handled.

Date: Thu, 30 May 2013 18:44:20 -0700

**Comment by CoolCapri** [comment]
Great
