### ISSUE TITLE
Let the Choice of Number of Buses and Biking Distances Work

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#157]
Users can now type Number of Buses and Biking Distance on SearchActivity. It seems that the routes returned are still not affected by these numbers.

**Comment by CoolCapri** [comment]
@alaurenz

**Comment by dutchscout** [comment]
This feature is pending, but it belongs in the doRequest() method.
See this issue: https://github.com/alaurenz/metrobike/issues/136

**Comment by dutchscout** [comment]
This has been written, but I'm testing before commit...
