### ISSUE TITLE
Allow user to set bicycling distance threshold using slider

### ISSUE THREAD

**Issue by alaurenz** [alaurenz/metrobike#158]
This would be a cool feature to add but we probably wont have enough time for it. It would be a slider where on one side is a bicycle icon and the other a bus icon which sets a threshold in the SmartAlgorithm which affects the amount of bicycling vs. bus when it looks for routes. If the slider is closer to the bus it would tend to find routes with less bicycling, etc.

**Comment by CoolCapri** [comment]
This is doable but it requires ui, backend and algorithm to decide what range, jump, and ratio would the slider have for adding one.
