### ISSUE TITLE
Get Android UI/Application Exerciser Monkey running on a device

### ISSUE THREAD

**Issue by alaurenz** [alaurenz/metrobike#159]

**Comment by alaurenz** [comment]
I figured out how to do this. It is quite simple just plug the device into the computer and run the following command in a terminal:

/path/to/adt-bundle/sdk/platform-tools/adb shell monkey -p com.HuskySoft.metrobike --pct-syskeys 0 --pct-majornav 0 <NUM ACTIONS FOR MONKEY TO PERFORM>

NOTE: replace /path/to/adt-bundle/ with the path on your machine.

The flags '--pct-syskeys 0 --pct-majornav 0' tell the monkey not to press system keys or back/home button. Without these flags I find that the monkey exits the app quickly:

For more documentation on monkey:
http://developer.android.com/tools/help/monkey.html

**Comment by CoolCapri** [comment]
Great. Did you successfully get rid of the null pointer exception problem when you start the app?

**Comment by sw11** [comment]
Thanks, I also need to add how many count in order to run.
So just add -v 500 
You can change the number if you want
