### ISSUE TITLE
Cancelable Feature Enhancements

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#165]
Thank you for providing this important fature. I have added it to UI and you may want to try it. We may have some enhancement on this feature: 
1. It takes some time to finish canceling (because backend will retry for 5 times), and during the join, the UI may look like freezing (but it is still working, just slow). Would you mind reducing the number of trial or adjusting some waiting time?
1. After canceling, the error message is not that helpful (showing connection error instead of "cancel error")

**Comment by dutchscout** [comment]
To fix the freezing, you could spawn a thread to run the disable/Thread.join/enable process.

To fix the error message, you could set a flag in the UI like ignoreResults to tell the doRequest() thread that it was cancelled.

For timeouts, we could possibly reduce the retry count... @alaurenz @coreyh3 any opinions?

**Comment by CoolCapri** [comment]
I have improved the UI.
