### ISSUE TITLE
Random letters reading from file

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#168]
If we type Chinese character to address box, the system will save it correctly since it is in memory. When we completely exit the app and restart it, the history in Chinese will be random letters (English address is fine). Please save and read characters correctly.

**Comment by sw11** [comment]
That's because when converting byte to string, it doesn't convert exactly back to Chinese. 
I will look into it and will fix it before Friday.
Thanks

**Comment by CoolCapri** [comment]
Is this a little hard to do?

**Comment by sw11** [comment]
It's done!
