### ISSUE TITLE
Figure out how to get the app on a projector

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#170]
For the demo on Monday morning

**Comment by dutchscout** [comment]
I figured out that we should really allow landscape mode for the app to be shown on a projector.  At least on the Xoom, the app is shown sideways AND 80 pixels are cut off the left of the screen (where our Route buttons are) because that's normally where the Android system bar goes (so the tablet cuts it off when showing on the projector).

I plan to make 2 .apk files this weekend: MetroBike_V2.apk and MetroBike_V2_demo.apk

The only difference will be that the demo will have the 'portrait' requirement removed so we can show it well on a projector.

Any complaints / suggestions?

**Comment by CoolCapri** [comment]
I am OK with this, but I am afraid that other UI people will not have enough time to change the layout if there are a lot to be done.

**Comment by dutchscout** [comment]
I tested it out (removing the 'portrait' requirement) and everything I tried seemed to just work.
I'm not planning on us adding that as a specific feature, just changing the manifest.

**Comment by sw11** [comment]
Just to be save, shall we change the manifest from portrait to landscape? 
We don't want to rotate the app while we are presenting.

**Comment by dutchscout** [comment]
Nope - the projector mode forces the app into landscape unless the app
insists on portrait-only.

Sent from my iPhone

On Jun 8, 2013, at 22:10, sw11 notifications@github.com wrote:

Just to be save, shall we change portrait to landscape?
We don't want to rotate the app while we are presenting.

—
Reply to this email directly or view it on
GitHubhttps://github.com/alaurenz/metrobike/issues/170#issuecomment-19161030
.

**Comment by dutchscout** [comment]
Bringing a projector tomorrow morning!
