### ISSUE TITLE
Go back to main activity after changing locale?

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#171]
Do we need to go back to the main activity after changing the locale?
As we need to "refresh" the UI.

**Comment by CoolCapri** [comment]
If it is not possible to change the whole UI locale as you change maptype, I think it is OK.

**Comment by CoolCapri** [comment]
Many applications on PC or Android requires user to restart when they select a different language. Maybe make a warning before user click OK to change?

**Comment by sw11** [comment]
Ok thanks
