### ISSUE TITLE
Finish posting phase documents

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#18]
According to the specs for this phase:

<b>Requirements Outline</b> and <b>Use Case</b> documents are to be submitted "by checking them into your version control system on GitHub".  However, the spec also says 'Create additional wiki pages... representing the following use case documents" :P

The <b>UI prototype</b> may be submitted "through GitHub as well if you like... you may also bring it to lecture on its due date [Monday@10:30 am] to turn it in at the beginning of lecture".

I can't seem to find where we're supposed to post the <b>ZFR instructions document</b>.

Since formatting on the wiki is pretty tedious, I believe we could simply check .pdf files into the repo (in a new folder called Docs or something) and link to those files from our wiki.  In fact, contrary to what I thought before, it looks like we can download individual files from inside our repository by accessing the file url.  For example, our HuskySoft logo is <a href="https://raw.github.com/alaurenz/metrobike/master/HelloMetroBike/res/drawable-ldpi/husky_soft.png">here</a>.  I think we should try to do this for our documents:

<ol><li>Create pdf's based on our Google Docs</li>
<li>Place these in a new folder in the repository</li>
<li>Link to the documents from our wiki</li>
</ol>

What do you think?

**Comment by CoolCapri** [comment]
I have asked Meg and she said any reasonable way to submit ZFR instructions would be fine (Wiki page, GitHub Repo, or the website that has our apk). I think Google Docs is also fine (do we need to make this folder public?) I think putting all docs in a folder in GitHub Repo is better than others.

**Comment by coreyh3** [comment]
Updated the SRS with formatting and the profitability section.

**Comment by dutchscout** [comment]
Done!  You can find links to all of the docs here:
https://github.com/alaurenz/metrobike/wiki/Phase-1-Documents-%28ZFR-SRS%29

**Comment by csmengwan** [comment]
Thank you Jaylen

At 2013-04-22 13:29:00,dutchscout notifications@github.com wrote:

Done! You can find links to all of the docs here:
https://github.com/alaurenz/metrobike/wiki/Phase-1-Documents-%28ZFR-SRS%29

¡ª
