### ISSUE TITLE
Location Class get longitude and latitude

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#40]
How do I get the longitude and latitude from a location class?

**Comment by dutchscout** [comment]
Oops; we need getters for these (no setters, though, since I believe Location should be immutable).

**Comment by coreyh3** [comment]
As is, I do not believe you can.  We should probably fix that.  I'll add in the functionality in the next push I make.
Corey
Date: Thu, 2 May 2013 17:27:09 -0700
