### ISSUE TITLE
Implement basic Details activity or something similar

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#56]
Our use case promises that we will get directions for our user.  Although the directions are being plotted on the map, our TA could argue we're not actually giving directions because we aren't listing the steps.  To be ready for our Alpha checkpoint, we should either:

(1) Implement the Details page to display basic text direction steps

(2) Add an overlay window or something to show a list of text steps.

I added a convenience method to the Route class (and Leg class) that lets you easily grab the list of text-directions for each step.  Here is an example of how to use it (after a call to doRequest or doLiveRequest):

```
        // Print current list of steps to the log
        List<String> textDirections = dReq.getSolutions().get(0).directionStepsText();
        for (String s : textDirections) {
            Log.v("Directions", s);
        }
```

**Comment by csmengwan** [comment]
Xinyun is on the details page, I will tell her to commit her current work to see if it is good for this request.
