### ISSUE TITLE
weird error in xml

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#62]
@meganca @smile76054789 
I got a weird error in this line of code in xml:
xmlns:android="http://schemas.android.com/apk/res/android"
It said that Unexpected namespace prefix "xmlns" found for tag LinearLayout
The error goes away every time when I clean the project.
Can someone tell me whats going on here?

**Comment by CoolCapri** [comment]
Each xml file should contain only one xmlns:android="http://schemas.android.com/apk/res/android", and it should be the one in its main(outermost) Layout. Other inner layouts should not have this attribute. Does that help?

**Comment by sw11** [comment]
Yes, currently I just delete the duplicate one. Thanks
