### ISSUE TITLE
Some Known bugs/flaws in search activity that should be resolved in the Beta phase

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#65]
1. SearchActivity.java currently leaves a block of checkstyle makers because of dummy history entires. It will be removed once the history function is finished in the next phases. @sw11 
2. The UI of SearchActivity does not prevent users from picking a PAST date or time, and this limitation can be implemented in the next phase. @dutchscout Do we need this limitation?

**Comment by dutchscout** [comment]
It should be fairly simple to reject past date/time, although some group members pointed out that Google Maps allows queries for the past.  We should discuss this at our next meeting.  If we decide to add it, we will add it to beta phase.

**Comment by dutchscout** [comment]
This issue has two parts.

1) Are the dummy history entries gone from SearchActivity?  I think they are...

2) Picking a date in the past seems ok for now...

Any objections to closing this issue?

**Comment by CoolCapri** [comment]
I think we can close this issue.
