### ISSUE TITLE
Keep main page or not

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#68]
Should our app just go to the search Page when launched, there is no reason to go to the main page at his phase

**Comment by dutchscout** [comment]
Good question.  Perhaps we can discuss this at our next meeting?  I'd rather not cut it out for the alpha phase, just in case deleting it accidentally introduces a bug.

**Comment by alaurenz** [comment]
Yeah I think the app should just go directly to the search page. I dont see any point to having that start page with a single button on it.

**Comment by CoolCapri** [comment]
Or how about adding a normal map showing current location of the user in MainActivity? I think directly pops up a searchActivity to user would be a little confusing and overwhelming to users.

**Comment by dutchscout** [comment]
Note: At the moment, the main page (with no Google Maps background) allows us to at least launch the app on an emulator (launching to a Google Maps page would likely crash the app, as the Results page crashes on a null map on the emulator at the moment).

**Comment by dutchscout** [comment]
In our group meeting, we voted to keep the main page but add a google maps fragment behind it showing the current location.  An issue for adding this has been created for V1 phase here: https://github.com/alaurenz/metrobike/issues/119

Closing the current issue...
