### ISSUE TITLE
Add connection to bike + bus directions to app

### ISSUE THREAD

**Issue by coreyh3** [alaurenz/metrobike#7]

**Comment by dutchscout** [comment]
Working on finishing this now...

**Comment by csmengwan** [comment]
I fixed logo stuff., can you see lit?

ÔÚ 2013-04-19 09:22:46£¬dutchscout notifications@github.com Ð´µÀ£º

Working on finishing this now...

¡ª

**Comment by dutchscout** [comment]
Yes, the logo is working.  Thanks!

**Comment by sw11** [comment]
I can see it, it works.
Thanks a lot~

**Comment by dutchscout** [comment]
This should be done now...
Don't forget to pull + clean the project (in Eclipse, Project-> Clean...-> Clean all projects)
