### ISSUE TITLE
BackEnd Crash on third history search(Schmitz Hall option)

### ISSUE THREAD

**Issue by csmengwan** [alaurenz/metrobike#70]

**Comment by dutchscout** [comment]
More information please!

**Comment by dutchscout** [comment]
Nevermind, I found the crash... working on it now....

**Comment by dutchscout** [comment]
Ahah!  Some hardcoded testing output was crashing the backend (the code assumed there were at least 3 steps).  This code wasn't necessary, so I'm getting rid of it.

Pushing fix in a couple minutes.

**Comment by dutchscout** [comment]
Fix pushed.  Please reopen this issue if the problem resurfaces.
