### ISSUE TITLE
Enhance activities and android life cycle in Beta version

### ISSUE THREAD

**Issue by sw11** [alaurenz/metrobike#78]
For the beta version, I will add the android life cycle so that we can avoid to create lots of intent objects.
I will also refactor some history classes and add more feature in settings, history and about activities.

**Comment by CoolCapri** [comment]
I have already fixed the life cycle. I think you can put more time on History

**Comment by dutchscout** [comment]
Any progress on this?

**Comment by csmengwan** [comment]
I think it is already fixed. You can try it out Jaylen.

**Comment by CoolCapri** [comment]
This is fixed for Beta phase. We can make it better for V1 if you have more suggestions.
