### ISSUE TITLE
Add transit times to Step objects

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#79]
Currently, our system says to catch a bus, but it doesn't say when (!)

This will require work from both the ui and backend teams.

**Comment by dutchscout** [comment]
We also need to add bus numbers here.

**Comment by dutchscout** [comment]
Use test-driven development for this.

**Comment by alaurenz** [comment]
I completed this by adding a TransitDetails object which is stored in each transit step (contains all relevant info about the transit such as bus numbers, times, names, etc). Also added unit tests for all of this object's methods.
