### ISSUE TITLE
Replace Android Log statements with System.out.println

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#81]
Goal: Make backend completely Java code.

**Comment by coreyh3** [comment]
I replaced it with .err?  That was what you mentioned to me in lecture yesterday.  Should it have been .out?

**Comment by dutchscout** [comment]
I believe .out ~= Log.v and .err ~= Log.e

.err should be correct (sorry about the confusion)

**Comment by dutchscout** [comment]
Thanks @coreyh3 for your help with this!  I think we can close this issue, at least for now...
