### ISSUE TITLE
Backend refactoring causes app to crash

### ISSUE THREAD

**Issue by alaurenz** [alaurenz/metrobike#85]
After the backend was refactored (put into pure Java code) upon launching the app on an Android the app loads but after entering start and end locations and clicking "Find" the app crashes. There logcat error is:
Could not find class 'com.HuskySoft.metrobike.backend.DirectionsRequest', referenced from method com.HuskySoft.metrobike.ui.SearchActivity$DirThread.run

**Comment by dutchscout** [comment]
I believe this has been fixed with the re-integration of the backend code.

**Comment by dutchscout** [comment]
Closing this for now.  Please re-open if this is still a problem.
