### ISSUE TITLE
Broken build: Need to add the actual HuskySoft logo file itself to the repo (git add...)

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#9]
Comment

**Comment by sw11** [comment]
issue: What I type:
git commit -am "<my comment>" 
git push origin master
It adds my modified xml file and commit and then push it into the master.
However, it didn't add the new files, which is the picture file itself. 
By solving this:
git add <the picture file path itself>
git commit -m "<my comment>"
git push origin master
- git status to check the current status *

**Comment by CoolCapri** [comment]
Can you type

git add res/
git commit -m "add logo"
git push origin master

to upload all files to this repo?

**Comment by csmengwan** [comment]
I fixed it

**Comment by sw11** [comment]
It works now. Thanks
