### ISSUE TITLE
Adding Address Selection Function in Backend

### ISSUE THREAD

**Issue by CoolCapri** [alaurenz/metrobike#92]
If user types a vague address, such as University Village, should we pop up a list (with a precise address) to let user choose which University Village he wants?

If this is doable in Beta, I will work on UI to first check the origin/destination, get a list of addresses and display them to let user to choose, and send precise address to backend again to request for routes.

**Comment by dutchscout** [comment]
This would be a fairly large addition to the backend.  We would need to add:
- URL creation for this kid of request
- Parsing capabilities
- A new structure to represent the information
- A class to represent the request and hold error messages.

(+ the UI elements)

Is this something we really want to do? We'd be adding another library to
our app to do this.

On May 16, 2013, at 10:34, Shuo Wang notifications@github.com wrote:

If user types a vague address, such as University Village, should we pop up
a list (with a precise address) to let user choose which University Village
he wants?

If this is doable in Beta, I will work on UI to first check the
origin/destination, get a list of addresses and display them to let user to
choose, and send precise address to backend again to request for routes.

—
Reply to this email directly or view it on
GitHubhttps://github.com/alaurenz/metrobike/issues/92
.

**Comment by CoolCapri** [comment]
This is just a thought. I know it takes a large amount of time. Maybe we can make this an extension feature.

**Comment by dutchscout** [comment]
I don't see this happening in beta phase; my estimate is up to 9 hours of work in the backend to get it completely working, plus time for testing.  I'll switch this to V1 phase for now, but I'd rather not spend that much time adding an extra feature unless we decide this is very important.
