### ISSUE TITLE
Change button text descriptions (from section Thu 5/16)

### ISSUE THREAD

**Issue by dutchscout** [alaurenz/metrobike#97]
Created from previous issue: https://github.com/alaurenz/metrobike/issues/91

Examples:
Search (on main page) -> Start search
Details -> Show steps
Result -> Show route

**Comment by CoolCapri** [comment]
@csmengwan Do you have time to change the appearance of the button so that it is suitable for showing the new text? If not, I will change it.

**Comment by CoolCapri** [comment]
I have changed them (adding descriptions on main page and changing result to route). I am leaving details unchanged because "show steps" is long for a button, and we can change it once we finalize the UI look in V1.
